version: "3"

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    env_file: .env
    restart: unless-stopped
    networks: 
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    expose:
    - "9000"
    env_file: .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
    - "443:443"
    env_file: .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress


networks:
  inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/victor/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type : none
      o: bind
      device: /home/victor/data/wordpress
